# Generated by Django 6.0.4 on 2026-06-13 07:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='credit_balance',
            field=models.DecimalField(decimal_places=3, default=0, help_text="User's current credit balance", max_digits=12, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
