# Generated by Django 6.0.4 on 2026-05-10 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credit_per_conversation', models.FloatField(default=1, help_text='Credits deducted per conversation')),
                ('default_system_prompt', models.TextField(default='You are an AI customer support assistant.\n\n<config>\n    language: bengali\n    voice_tone: friendly\n    greeting: Assalamu Alaikum\n    response_size: medium, none-repeat\n</config>\n\n<conversation-flow>\n    1. greeting + your intro + business intro + cta\n    ... follow up\n</conversation-flow>', help_text='Default system prompt for the AI.')),
                ('default_business_info', models.TextField(default='Name:\nContact:\n  - Phone:\n  - Whatsapp:\n  - Email:\nAddress:\nOwner: \n\nDescription(mission/vision): ', help_text='Default business information for the AI.')),
                ('default_ai_model', models.CharField(default='google/gemini-3.1-flash-lite-preview', help_text='Default AI model name from OpenRouter, e.g. provider/model', max_length=100)),
                ('global_openrouter_api_key', models.CharField(blank=True, help_text='Global OpenRouter API key.', max_length=1024, null=True)),
            ],
        ),
    ]
