# Generated by Django 5.2.8 on 2026-05-14 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_siteconfig_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='free_credits_on_signup',
            field=models.PositiveIntegerField(default=10, help_text='Free credits per ip address'),
        ),
    ]
