# Generated by Django 5.2.8 on 2026-05-15 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_siteconfig_free_credits_on_signup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteconfig',
            name='default_system_prompt',
            field=models.TextField(default='You are an AI customer support assistant.\n\n<config>\n    language: bengali\n    voice_tone: friendly\n    greeting: Assalamu Alaikum\n    response_size: medium, none-repeat\n    response: strict to text/plain, ignore markdown\n</config>\n\n<conversation-flow>\n    1. greeting + your intro + business intro + cta\n    ... follow up\n</conversation-flow>', help_text='Default system prompt for the AI.'),
        ),
    ]
