# Generated by Django 5.2.8 on 2026-05-16 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_siteconfig_default_system_prompt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteconfig',
            name='default_system_prompt',
            field=models.TextField(default='You are an AI customer support assistant.\n\n<config>\n    language: bengali\n    tone: friendly\n    response_size: medium, none-repeat\n    response: strict to text/plain, ignore markdown\n</config>\n\n<conversation-flow>\n    1. আসসালামু আলাইকুম + your intro + business intro + cta\n    ... follow up\n</conversation-flow>', help_text='Default system prompt for the AI.'),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='free_credits_on_signup',
            field=models.PositiveIntegerField(default=10),
        ),
    ]
