# Generated by Django 6.0.4 on 2026-05-25 12:49

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_infopage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infopage',
            name='content',
            field=django_ckeditor_5.fields.CKEditor5Field(),
        ),
    ]
