# Generated by Django 6.0.4 on 2026-05-25 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_infopage_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='infopage',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
