# Generated by Django 6.0.4 on 2026-05-25 19:18

import django_jsonform.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_infopage_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_title', models.CharField(max_length=255)),
                ('hero_subtitle', models.CharField(max_length=500)),
                ('phone_chat', django_jsonform.models.fields.JSONField(default=dict)),
                ('brands_title', models.CharField(default='Trusted by leading brands', max_length=255)),
                ('brands_subtitle', models.CharField(default='We work with the leading brands in Banglaladesh', max_length=500)),
                ('brands', django_jsonform.models.fields.JSONField(default=list, help_text='List of brands with name and logo URL')),
                ('features_title', models.CharField(default='Features', max_length=255)),
                ('features_subtitle', models.CharField(default='The features we offer', max_length=500)),
                ('features', django_jsonform.models.fields.JSONField(default=list, help_text='List of features with title, subtitle and image URL')),
                ('reviews_title', models.CharField(default='What our customers say', max_length=255)),
                ('reviews_subtitle', models.CharField(default='Customer reviews and testimonials', max_length=500)),
                ('reviews', django_jsonform.models.fields.JSONField(default=list, help_text='List of reviews with name, designation, photo URL, rating and comment')),
                ('faq_title', models.CharField(default='Frequently Asked Questions', max_length=255)),
                ('faqs', django_jsonform.models.fields.JSONField(default=list, help_text='List of frequently asked questions with question and answer')),
                ('footer_text', models.CharField(max_length=255)),
                ('social_links', django_jsonform.models.fields.JSONField(default=list)),
                ('link_groups', django_jsonform.models.fields.JSONField(default=list)),
            ],
        ),
    ]
