# Generated by Django 6.0.4 on 2026-05-26 04:00

import django_jsonform.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_homepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='meta_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='meta_keywords',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='title',
            field=models.CharField(default='BikriAI - AI powered customer service', max_length=255),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='phone_chat',
            field=django_jsonform.models.fields.JSONField(default=list),
        ),
    ]
