# Generated by Django 6.0.4 on 2026-05-26 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_homepage_meta_description_homepage_meta_keywords_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='see_demo_url',
            field=models.CharField(default='#', max_length=255),
        ),
    ]
