# Generated by Django 6.0.4 on 2026-05-26 09:57

import django_jsonform.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_homepage_see_demo_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='hero_tag',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='homepage',
            name='brands',
            field=django_jsonform.models.fields.JSONField(blank=True, default=list, help_text='List of brands with name and logo URL', null=True),
        ),
    ]
