# Generated by Django 6.0.4 on 2026-06-04 15:34

import django_jsonform.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_homepage_hero_tag_alter_homepage_brands'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='demo_steps',
            field=django_jsonform.models.fields.JSONField(default=list, help_text='List of steps for the watch demo section'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='demo_steps_title',
            field=models.CharField(default='In this video you will learn to', max_length=255),
        ),
        migrations.AddField(
            model_name='homepage',
            name='demo_subtitle',
            field=models.CharField(default='See how simple it is to get started in just a few minutes', max_length=500),
        ),
        migrations.AddField(
            model_name='homepage',
            name='demo_title',
            field=models.CharField(default='Watch the demo, How it works', max_length=255),
        ),
        migrations.AddField(
            model_name='homepage',
            name='demo_video_url',
            field=models.CharField(default='/static/videos/demo.mp4', max_length=255),
        ),
        migrations.AddField(
            model_name='homepage',
            name='industries',
            field=django_jsonform.models.fields.JSONField(default=list, help_text='List of industries with name, icon, desc and badge'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='industries_subtitle',
            field=models.CharField(default='Discover how BikriAI automates customer interactions and drives sales for your specific business niche.', max_length=500),
        ),
        migrations.AddField(
            model_name='homepage',
            name='industries_title',
            field=models.CharField(default='Who need it?', max_length=255),
        ),
        migrations.AddField(
            model_name='homepage',
            name='integrations',
            field=django_jsonform.models.fields.JSONField(default=list, help_text='List of integrations with name, icon and desc'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='integrations_subtitle',
            field=models.CharField(default='We provide integrations that you need most.', max_length=500),
        ),
        migrations.AddField(
            model_name='homepage',
            name='integrations_title',
            field=models.CharField(default='Integrations Available', max_length=255),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='brands_subtitle',
            field=models.CharField(default='We work with the leading brands in Bangladesh', max_length=500),
        ),
    ]
