# Generated by Django 6.0.4 on 2026-06-05 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_galleryitem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='galleryitem',
            options={'ordering': ['-uploaded_at'], 'verbose_name': 'File', 'verbose_name_plural': 'Files'},
        ),
    ]
