# Generated by Django 6.0.4 on 2026-06-06 13:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_galleryitem_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='demo_steps',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='demo_steps_title',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='demo_subtitle',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='demo_title',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='demo_video_url',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='features',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='features_subtitle',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='features_title',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='industries',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='industries_subtitle',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='industries_title',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='integrations',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='integrations_subtitle',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='integrations_title',
        ),
        migrations.CreateModel(
            name='HomePageSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('html', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('homepage', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='core.homepage')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
