# Generated by Django 6.0.4 on 2026-06-08 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_remove_homepage_demo_steps_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteconfig',
            name='credit_per_conversation',
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='credit_per_comment_analysis',
            field=models.FloatField(default=0.1, help_text='Sentiment analysis credit per comment.'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='credit_per_reply',
            field=models.FloatField(default=1, help_text='Starting credit per ai reply.'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='credit_per_reply_increment',
            field=models.FloatField(default=0.0002, help_text='Credit increment rate per token.'),
        ),
    ]
