# Generated by Django 6.0.4 on 2026-06-08 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_remove_siteconfig_credit_per_conversation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='pricing_subtitle',
            field=models.CharField(default='We offer competitive pricing for your convenience', max_length=500),
        ),
        migrations.AddField(
            model_name='homepage',
            name='pricing_title',
            field=models.CharField(default='Pricing', max_length=255),
        ),
    ]
