# Generated by Django 6.0.4 on 2026-06-09 05:12

import django_ckeditor_5.fields
import django_jsonform.models.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_homepage_pricing_subtitle_homepage_pricing_title'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Popup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('content', django_ckeditor_5.fields.CKEditor5Field()),
                ('popup_buttons', django_jsonform.models.fields.JSONField(default=list)),
                ('users', models.ManyToManyField(help_text='Users who will see this popup.', related_name='popups', to=settings.AUTH_USER_MODEL)),
                ('users_read', models.ManyToManyField(blank=True, help_text='Users who have read (closed) this popup.', null=True, related_name='popup_read', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
