# Generated by Django 6.0.4 on 2026-06-09 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_popup'),
    ]

    operations = [
        migrations.RenameField(
            model_name='popup',
            old_name='popup_buttons',
            new_name='buttons',
        ),
    ]
