# Generated by Django 6.0.4 on 2026-06-09 06:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_rename_popup_buttons_popup_buttons'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='popup',
            options={'ordering': ['-updated_at', '-created_at']},
        ),
        migrations.AddField(
            model_name='popup',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='popup',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='popup',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
