# Generated by Django 6.0.4 on 2026-06-09 07:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_alter_popup_options_popup_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='popup',
            name='users_read',
            field=models.ManyToManyField(blank=True, help_text='Users who have read (closed) this popup.', related_name='popup_read', to=settings.AUTH_USER_MODEL),
        ),
    ]
