# Generated by Django 6.0.4 on 2026-06-24 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_alter_popup_users_read'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteconfig',
            name='default_ai_model',
            field=models.CharField(default='google/gemini-3.1-flash-lite', help_text='Default AI model name from OpenRouter, e.g. provider/model', max_length=100),
        ),
    ]
