# Generated by Django 6.0.4 on 2026-06-25 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_alter_siteconfig_default_ai_model'),
    ]

    operations = [
        migrations.RenameField(
            model_name='siteconfig',
            old_name='credit_per_comment_analysis',
            new_name='credit_per_comment',
        ),
    ]
