# Generated by Django 6.0.4 on 2026-06-27 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_rename_credit_per_comment_analysis_siteconfig_credit_per_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='support_whatsapp_number',
            field=models.CharField(blank=True, null=True),
        ),
    ]
