# Generated by Django 6.0.4 on 2026-06-27 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_homepage_support_whatsapp_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='support_whatsapp_number',
            field=models.CharField(blank=True, help_text='e.g. 8801xxxxxxx', max_length=100, null=True),
        ),
    ]
