# Generated by Django 6.0.4 on 2026-07-03 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_alter_homepage_support_whatsapp_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='extra_head',
            field=models.TextField(blank=True, help_text='Additional HTML to include in the <head> section of the page', null=True),
        ),
    ]
