# Generated by Django 6.0.4 on 2026-07-13 12:28

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_homepage_extra_head'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteconfig',
            name='credit_per_comment',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.1'), help_text='Sentiment analysis credit per comment.', max_digits=8),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='credit_per_reply',
            field=models.DecimalField(decimal_places=3, default=Decimal('1'), help_text='Starting credit per ai reply.', max_digits=8),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='credit_per_reply_increment',
            field=models.DecimalField(decimal_places=6, default=Decimal('0.0002'), help_text='Credit increment rate per token.', max_digits=8),
        ),
    ]
