# Generated by Django 6.0.4 on 2026-05-10 14:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessProfile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='profile_pic')),
                ('platform_id', models.CharField(max_length=100, verbose_name='ID on platform')),
                ('platform_name', models.CharField(choices=[('facebook', 'Facebook'), ('whatsapp', 'Whatsapp')], max_length=100)),
                ('_platform_access_token', models.CharField(blank=True, db_column='platform_access_token', max_length=1024, null=True)),
                ('system_prompt', models.TextField(blank=True, help_text='Instructions for the AI to follow.', null=True)),
                ('business_info', models.TextField(blank=True, help_text='Provide information about your business.', null=True)),
                ('ai_model', models.CharField(blank=True, help_text='AI model name from OpenRouter, e.g. provider/model', max_length=100, null=True)),
                ('openrouter_api_key', models.CharField(blank=True, help_text='This will be used if provided otherwise default.', max_length=1024, null=True)),
                ('reply_enabled', models.BooleanField(default=True, help_text='Enable or disable ai', verbose_name='AI Reply')),
                ('auto_pause', models.BooleanField(default=True, help_text='Messenger only', verbose_name='Auto Pause on Admin reply')),
                ('pause_timeout', models.PositiveIntegerField(default=15, help_text='Time to auto resume replying after paused. Messenger only', verbose_name='Auto Pause Timeout (minutes)')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('platform_id', 'platform_name')},
            },
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reply_enabled', models.BooleanField(default=True)),
                ('json', models.JSONField(default=[])),
                ('business_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='business_profile.businessprofile')),
            ],
            options={
                'ordering': ['-updated_at', '-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('url', models.URLField()),
                ('file_type', models.CharField(max_length=255)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='business_profile.conversation')),
            ],
            options={
                'ordering': ['-updated_at', '-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('platform_id', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='profile_pic')),
                ('gender', models.CharField(blank=True, max_length=100, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('business_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='business_profile.businessprofile')),
            ],
            options={
                'ordering': ['-updated_at', '-created_at'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='conversation',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='business_profile.customer'),
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mid', models.CharField(max_length=255)),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant'), ('human_agent', 'Human Agent')], max_length=100)),
                ('content', models.TextField()),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='business_profile.conversation')),
            ],
            options={
                'ordering': ['-updated_at', '-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fields', models.JSONField()),
                ('business_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='business_profile.businessprofile')),
                ('conversation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='business_profile.conversation')),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='business_profile.customer')),
            ],
            options={
                'ordering': ['-updated_at', '-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, help_text='Description of the product, including variants, discounts and more.', max_length=512, null=True)),
                ('price', models.IntegerField(help_text='In BDT')),
                ('view_url', models.URLField(blank=True, help_text="Clicking View button will open this url. AI don't see this.", null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Enable or disable product')),
                ('priority', models.PositiveIntegerField(db_index=True, default=0)),
                ('business_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='business_profile.businessprofile')),
            ],
            options={
                'ordering': ['priority', '-updated_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MediaFiles',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(upload_to='media_files')),
                ('file_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('audio', 'Audio'), ('file', 'File')], default='file', max_length=100)),
                ('transcription', models.TextField(blank=True, help_text='AI Cannot see the fill every time. Describe the content of the file for ai to understand.', max_length=512, null=True)),
                ('priority', models.PositiveIntegerField(db_index=True, default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('business_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_files', to='business_profile.businessprofile')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_media_files', to='business_profile.product')),
            ],
            options={
                'verbose_name': 'Media File',
                'verbose_name_plural': 'Media Files',
                'ordering': ['priority', '-updated_at', '-created_at'],
            },
        ),
    ]
