# Generated by Django 6.0.4 on 2026-05-11 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_profile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='json',
            field=models.JSONField(default=list),
        ),
    ]
