# Generated by Django 5.2.8 on 2026-05-14 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business_profile', '0004_alter_conversation_options_alter_message_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='businessprofile',
            options={'ordering': ['-updated_at', '-created_at']},
        ),
        migrations.RemoveField(
            model_name='businessprofile',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='businessprofile',
            name='restored_at',
        ),
        migrations.RemoveField(
            model_name='businessprofile',
            name='transaction_id',
        ),
    ]
