# Generated by Django 5.2.8 on 2026-05-15 06:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_profile', '0005_alter_businessprofile_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderFild',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=32)),
                ('description', models.CharField(max_length=128)),
                ('order', models.PositiveIntegerField(default=0)),
                ('business_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_fields', to='business_profile.businessprofile')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
