# Generated by Django 5.2.8 on 2026-05-15 08:09

import django_jsonform.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business_profile', '0006_orderfild'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessprofile',
            name='order_fields',
            field=django_jsonform.models.fields.JSONField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='OrderFild',
        ),
    ]
