# Generated by Django 5.2.8 on 2026-05-15 09:12

import django_jsonform.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business_profile', '0008_alter_businessprofile_order_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessprofile',
            name='order_fields',
            field=django_jsonform.models.fields.JSONField(default=['name', 'phone']),
        ),
    ]
