# Generated by Django 5.2.8 on 2026-05-15 10:13

import django_jsonform.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business_profile', '0009_alter_businessprofile_order_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='fields',
            field=django_jsonform.models.fields.JSONField(),
        ),
    ]
