# Generated by Django 5.2.8 on 2026-05-16 09:29

import django_jsonform.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_profile', '0010_alter_order_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='json',
            field=django_jsonform.models.fields.JSONField(default=[]),
        ),
        migrations.AlterField(
            model_name='order',
            name='fields',
            field=django_jsonform.models.fields.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='product',
            name='view_url',
            field=models.URLField(blank=True, help_text="Clicking Details button will open this url. AI don't see this.", null=True),
        ),
    ]
