# Generated by Django 5.2.8 on 2026-05-16 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business_profile', '0011_alter_conversation_json_alter_order_fields_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='view_url',
        ),
    ]
