# Generated by Django 5.2.8 on 2026-05-18 00:35

import django.db.models.deletion
import django_jsonform.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_profile', '0012_remove_product_view_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentPreset',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('keywords', django_jsonform.models.fields.JSONField(default=list, help_text='List of keywords to match for this preset')),
                ('comment_text', models.TextField(help_text='The automated reply text if a keyword matches')),
                ('business_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_presets', to='business_profile.businessprofile')),
            ],
            options={
                'ordering': ['-updated_at', '-created_at'],
                'abstract': False,
            },
        ),
    ]
