# Generated by Django 5.2.8 on 2026-05-18 01:15

import django_jsonform.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business_profile', '0013_commentpreset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentpreset',
            name='keywords',
            field=django_jsonform.models.fields.JSONField(default=[''], help_text='List of keywords to match for this preset'),
        ),
    ]
