# Generated by Django 5.2.8 on 2026-05-18 08:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_profile', '0014_alter_commentpreset_keywords'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('comment_text', models.TextField(help_text='The comment text sent by the customer')),
                ('reply_text', models.TextField(blank=True, help_text='The reply text sent back to the customer', null=True)),
                ('sentiment_score', models.FloatField(default=0.0, help_text='Sentiment score by AI')),
                ('business_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_logs', to='business_profile.businessprofile')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_logs', to='business_profile.customer')),
            ],
            options={
                'ordering': ['-updated_at', '-created_at'],
                'abstract': False,
            },
        ),
    ]
