# Generated by Django 5.2.8 on 2026-05-18 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_profile', '0015_commentlog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentlog',
            name='customer',
        ),
        migrations.AddField(
            model_name='commentlog',
            name='psid',
            field=models.CharField(default=2323, help_text='The psid of the customer', max_length=100),
            preserve_default=False,
        ),
    ]
