# Generated by Django 5.2.8 on 2026-05-18 10:07

import apps.business_profile.models
import django_jsonform.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business_profile', '0016_remove_commentlog_customer_commentlog_psid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessprofile',
            name='order_fields',
            field=django_jsonform.models.fields.JSONField(default=apps.business_profile.models.default_order_fields),
        ),
        migrations.AlterField(
            model_name='commentpreset',
            name='keywords',
            field=django_jsonform.models.fields.JSONField(default=apps.business_profile.models.default_preset_keywords, help_text='List of keywords to match for this preset'),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='json',
            field=django_jsonform.models.fields.JSONField(default=list),
        ),
    ]
