# Generated by Django 5.2.8 on 2026-05-20 01:38

import django.db.models.deletion
import django_jsonform.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_profile', '0017_alter_businessprofile_order_fields_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessprofile',
            name='waba_id',
            field=models.CharField(blank=True, help_text='WhatsApp Business Account ID', max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='WhatsappTemplate',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('template_id', models.CharField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('language', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('components', django_jsonform.models.fields.JSONField(default=list)),
                ('business_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='whatsapp_templates', to='business_profile.businessprofile')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
