# Generated by Django 5.2.8 on 2026-05-20 05:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_profile', '0018_businessprofile_waba_id_whatsapptemplate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentlog',
            name='business_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_logs', to='business_profile.businessprofile', verbose_name='Facebook Page'),
        ),
        migrations.AlterField(
            model_name='commentlog',
            name='comment_text',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='commentlog',
            name='psid',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='commentlog',
            name='reply_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='commentlog',
            name='sentiment_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='commentpreset',
            name='business_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_presets', to='business_profile.businessprofile', verbose_name='Facebook Page'),
        ),
        migrations.AlterField(
            model_name='whatsapptemplate',
            name='components',
            field=models.JSONField(default=list),
        ),
    ]
