# Generated by Django 6.0.4 on 2026-05-24 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_profile', '0019_alter_commentlog_business_profile_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conversation',
            options={'permissions': (('can_undelete', 'Can undelete this object'),)},
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'permissions': (('can_undelete', 'Can undelete this object'),)},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'permissions': (('can_undelete', 'Can undelete this object'),)},
        ),
        migrations.RemoveField(
            model_name='conversation',
            name='restored_at',
        ),
        migrations.RemoveField(
            model_name='conversation',
            name='transaction_id',
        ),
        migrations.RemoveField(
            model_name='message',
            name='restored_at',
        ),
        migrations.RemoveField(
            model_name='message',
            name='transaction_id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='restored_at',
        ),
        migrations.RemoveField(
            model_name='order',
            name='transaction_id',
        ),
        migrations.AlterField(
            model_name='conversation',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, default=None, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, default=None, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, default=None, editable=False, null=True),
        ),
    ]
