# Generated by Django 6.0.4 on 2026-06-05 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_profile', '0021_alter_conversation_options_alter_message_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentpreset',
            name='reply_destination',
            field=models.CharField(choices=[('comment', 'Comment'), ('inbox', 'Inbox')], default='comment', max_length=100),
        ),
        migrations.AlterField(
            model_name='commentpreset',
            name='comment_text',
            field=models.TextField(help_text='The automated reply text if a keyword matches', verbose_name='Reply'),
        ),
    ]
