# Generated by Django 6.0.4 on 2026-06-06 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_profile', '0022_commentpreset_reply_destination_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessprofile',
            name='comments_reply_enabled',
            field=models.BooleanField(default=True, help_text='Enable or disable preseted comment reply', verbose_name='Preseted Comment Reply'),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='delete_negative_comments',
            field=models.BooleanField(default=False, help_text='Enable or disable deleting negative comments', verbose_name='Delete Negative Comment'),
        ),
    ]
