# Generated by Django 6.0.4 on 2026-06-06 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_profile', '0023_businessprofile_comments_reply_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessprofile',
            name='api_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='api_key',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='webhook_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='webhook_url',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
