# Generated by Django 6.0.4 on 2026-06-08 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_profile', '0024_businessprofile_api_enabled_businessprofile_api_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessprofile',
            name='knowledge',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='knowledge_token',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='businessprofile',
            name='api_key',
            field=models.CharField(blank=True, max_length=1024, null=True, unique=True),
        ),
    ]
