# Generated by Django 6.0.4 on 2026-06-13 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_profile', '0025_businessprofile_knowledge_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessprofile',
            name='ai_model',
            field=models.CharField(blank=True, choices=[('google/gemini-3.1-flash-lite', 'Gemini 3.1 Flash Lite'), ('deepseek/deepseek-v4-flash', 'Deepseek v4 Flash'), ('openai/gpt-oss-120b', 'GPT OSS 120B')], max_length=100, null=True),
        ),
    ]
