# Generated by Django 6.0.4 on 2026-06-14 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_profile', '0026_alter_businessprofile_ai_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='auto_paused',
            field=models.BooleanField(default=False, help_text='If paused due to admin reply'),
        ),
    ]
