# Generated by Django 6.0.4 on 2026-06-24 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_profile', '0027_conversation_auto_paused'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessprofile',
            name='auto_pause',
            field=models.BooleanField(default=True, verbose_name='Auto Pause on Admin reply'),
        ),
        migrations.AlterField(
            model_name='businessprofile',
            name='pause_timeout',
            field=models.PositiveIntegerField(default=15, help_text='Time to auto resume replying after paused.', verbose_name='Auto Pause Timeout (minutes)'),
        ),
        migrations.AlterField(
            model_name='mediafiles',
            name='transcription',
            field=models.TextField(blank=True, help_text='AI Cannot see the file every time. Describe the content of the file for ai to understand.', max_length=512, null=True),
        ),
    ]
