# Generated by Django 6.0.4 on 2026-07-12 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_profile', '0029_alter_businessprofile_ai_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='message_credit_used',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='conversation',
            name='tool_credit_used',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
