# Generated by Django 6.0.4 on 2026-07-12 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_profile', '0030_conversation_message_credit_used_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessprofile',
            name='ai_model',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
