# Generated by Django 6.0.4 on 2026-07-13 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business_profile', '0031_alter_businessprofile_ai_model'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-updated_at', '-created_at']},
        ),
        migrations.RemoveField(
            model_name='product',
            name='priority',
        ),
    ]
