# Generated by Django 6.0.4 on 2026-07-13 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_profile', '0032_alter_product_options_remove_product_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('paused', 'Paused'), ('delivered', 'Delivered'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=100),
        ),
    ]
