# Generated by Django 6.0.4 on 2026-07-13 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_profile', '0033_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='message_credit_used',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='tool_credit_used',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
    ]
