# Generated by Django 6.0.4 on 2026-07-18 10:44

import apps.business_profile.models
import django_jsonform.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business_profile', '0034_align_credit_decimal_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='fields',
            field=django_jsonform.models.fields.JSONField(default=apps.business_profile.models.default_order_fields_data),
        ),
    ]
