# Generated by Django 6.0.4 on 2026-05-11 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0002_creditpackage_site_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditpackage',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Whether this package is featured'),
        ),
    ]
