# Generated by Django 6.0.4 on 2026-05-12 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0003_creditpackage_is_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='credittransaction',
            name='balance_after',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
