# Generated by Django 5.2.8 on 2026-05-18 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0005_alter_credittransaction_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credittransaction',
            name='reason',
            field=models.CharField(choices=[('ai_conversation', 'AI Conversation'), ('comment_reply', 'Comment Reply'), ('purchase', 'Purchase'), ('free', 'Free'), ('refund', 'Refund')], max_length=100),
        ),
    ]
