# Generated by Django 6.0.4 on 2026-06-05 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0006_alter_credittransaction_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentattempt',
            name='manual_transaction_id',
            field=models.CharField(blank=True, help_text='Transaction ID submitted by user for manual payments', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='paymentattempt',
            name='payment_method',
            field=models.CharField(choices=[('bkash', 'bKash (Automatic)'), ('manual', 'Manual Payment')], default='bkash', max_length=20),
        ),
        migrations.AddField(
            model_name='paymentattempt',
            name='verified_at',
            field=models.DateTimeField(blank=True, help_text='When the manual payment was verified by admin', null=True),
        ),
    ]
