# Generated by Django 6.0.4 on 2026-06-09 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0007_paymentattempt_manual_transaction_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credittransaction',
            name='reason',
            field=models.CharField(choices=[('ai_reply', 'AI Reply'), ('comment', 'Comment'), ('purchase', 'Purchase'), ('free', 'Free'), ('refund', 'Refund')], max_length=100),
        ),
    ]
