# Generated by Django 6.0.4 on 2026-06-13 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0008_alter_credittransaction_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credittransaction',
            name='reason',
            field=models.CharField(max_length=100),
        ),
    ]
