# Generated by Django 6.0.4 on 2026-07-13 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0009_alter_credittransaction_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credittransaction',
            name='amount',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
        migrations.AlterField(
            model_name='credittransaction',
            name='balance_after',
            field=models.DecimalField(decimal_places=3, max_digits=12),
        ),
    ]
